version: '3.8'

services:
  spring-boot-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-demo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for local testing
  nginx:
    image: nginx:alpine
    container_name: spring-boot-demo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-boot-demo
    restart: unless-stopped

networks:
  default:
    name: spring-boot-demo-network